server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aopdemo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5 #????????
#      min-idle: 10 #???????
#      max-active: 20 #?????
#      web-stat-filter:
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #?????????
#      stat-view-servlet: #???????????????
#        login-username: druid
#        login-password: druid